apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-server
        image: leonsam2/my-repo-lab3-ls:1.0.0
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort  # ИЛИ LoadBalancer
  selector:
    app: web-app  # Важно: тот же selector что и в Deployment!
  ports:
  - port: 80        # Порт сервиса (внутри кластера)
    targetPort: 8000 # Порт контейнера
    nodePort: 30080  # Порт на ноде (30000-32767)